### ISSUE TITLE
Roster Sync - Lock wait timeout exceeded

### ISSUE THREAD

**Issue by rickhumphries** [elmsln/elmsln#1884]
v0.6.3

We have a custom page where students are allowed to set an email address for their account (this is saved to a custom email address field rather than the standard Drupal email address field). It seems like this may be causing issues since throughout the day, our website will crash at least once, and I can get multiple error messages in the logs of which there are two variations:

```
Site:           https://online.xyz.co.uk
Severity:       Error (3)
Timestamp:      2017-02-20 16:28:06
Type:           user
IP Address:     
Request URI:
https://online.xyz.co.uk/dashboard/profile/set-email
Referrer URI:
https://online.xyz.co.uk/dashboard/profile/set-email
User:           Username (37334)
Link:
Message:

PDOException: SQLSTATE[HY000]: General error: 1205 Lock wait timeout
exceeded; try restarting transaction: DELETE FROM {cache_entity_user}
WHERE  (cid IN  (:db_condition_placeholder_0)) ; Array
(
      [:db_condition_placeholder_0] => 37334
)
   in APDQCache->clear() (line 619 of
/var/www/elmsln/core/dslmcode/shared/drupal-7.x/modules/ulmus/apdqc/apdqc.cache.inc).
```
And
```
Site:           https://online.xyz.co.uk
Severity:       Error (3)
Timestamp:      2017-02-20 16:22:27
Type:           user
IP Address:     
Request URI:
https://online.xyz.co.uk/dashboard/profile/set-email
Referrer URI:
https://online.xyz.co.uk/dashboard/profile/set-email
User:           Username (36050)
Link:
Message:

PDOException: SQLSTATE[HY000]: General error: 1205 Lock wait timeout
exceeded; try restarting transaction: UPDATE {variable} SET
value=:db_update_placeholder_0
WHERE ( (name = :db_condition_placeholder_0) ); Array
(
      [:db_update_placeholder_0] => b:1;
      [:db_condition_placeholder_0] => drupal_http_request_fails
)
   in variable_set() (line 1230 of
/var/www/elmsln/core/dslmcode/cores/drupal-7/includes/bootstrap.inc).
```

**Comment by btopro** [comment]
answer in back channel

**Comment by rickhumphries** [comment]
Similar error, but not identical and seems to happen when saving a course node in the CIS which doesn't have any services setup in the course network. I get an Error 500 message (site cannot handle this request) and then shortly afterwards had a few emails come through with the following:
```
Site:           https://online.buttercupstraining.co.uk
Severity:       Error (3)
Timestamp:      2017-02-22 10:22:07
Type:           php
IP Address:     127.0.0.1
Request URI:    https://online.xyz.co.uk/
Referrer URI:
User:           Anonymous (0)
Link:
Message:

PDOException: SQLSTATE[HY000]: General error: 1205 Lock wait timeout
exceeded; try restarting transaction: DELETE FROM {cache_bootstrap}
WHERE  (cid = :db_condition_placeholder_0) ; Array
(
      [:db_condition_placeholder_0] => variables
)
   in cache_clear_all() (line 168 of
/var/www/elmsln/core/dslmcode/cores/drupal-7/includes/cache.inc).
```

**Comment by btopro** [comment]
https://github.com/elmsln/elmsln/issues/1637 in 070 should resolve this. There was a race condition that could occur in the background from common save operations. The sync / course save stuff has been refactored a bit in 070+ to help prevent these issues.

**Comment by rickhumphries** [comment]
@btopro  just checked to see whether this occurs on our dev site which has updated to 0.7.0 and it does still occur. Will send link via back channel

**Comment by btopro** [comment]
Related to a race condition between field collections and nodes.

Save course = save field collection (offering) and save from there field collection sections. This is 3+ entities on that one course save. What can happen (hard to trace) is that offering is in the process of saving and section is being saved. Section being acted upon says "oh who's my offering", it's there, then says "who's offering's course?" but this data isn't currently there since it's in the process of being saved. APDQC is saving this on a background thread (guessing here) which then causes the data to be correct if you look at it after the fact (cause it resolves) but at the moment of this call will 500 error because there's no course (which then doing a lookup that relies on course it gets pissed).
